
# 5 NumPy functions to make a Pizza

NumPy is a Python library developed to optimize mathematical (and not only) operations, that usually takes more time and effort when done with raw Python. 
NumPy optimize memory: since Python store everything as an "object", these take much more space than, for example, a simple int or a float. NumPy does this: it stores data for what they are and optimizing a lot of operations which would require much more code in Python.

These are the NumPy functions I chose in order to mimic the process of making a pizza!

- function 1 - np.squeeze
- function 2 - np.roll
- function 3 - np.flip
- function 4 - np.split
- function 5 - np.repeat


In [ ]:
import numpy as np

##### Firstly, let's **squeeze** our dough...
<img src="https://i.imgur.com/t8Qhfwx.jpg"></img>
## Function 1 - **np.squeeze**

The np.squeeze function helps us get rid of unnecessary one-dimensional lines. E.g. [[[7,8,9]]] would be squeezed in [7,8,9]. 

In [ ]:
# Example 1 - working 
arr1 = np.array([
      [
        [1,2,3]
      ]
    ])

print("This is our array:", arr1)
print("This is the current shape of the array", arr1.shape)

arr1_squeezed = np.squeeze(arr1)
print("This is our squeezed array", arr1_squeezed)
print("This is the new shape of the squeezed array", arr1_squeezed.shape)

This is our array: [[[1 2 3]]]
This is the current shape of the array (1, 1, 3)
This is our squeezed array [1 2 3]
This is the new shape of the squeezed array (3,)


We have used np.squeeze to get rid of extra one-dimensional lines, making it more versatile.


In [ ]:
# Example 2 - working
arr1 = np.array([
      [
        [1],
        [2],
        [3]
      ]
    ])

print("This is our array:\n", arr1)
print("This is the current shape of the array", arr1.shape)

##Squeezing axis=0

arr1_squeezed0 = np.squeeze(arr1, axis=0)
print("This is our squeezed array, along the axis=0\n", arr1_squeezed0)
print("This is the new shape of the squeezed array", arr1_squeezed0.shape)


##Squeezing axis=2

arr1_squeezed2 = np.squeeze(arr1, axis=2)
print("This is our squeezed array, along the axis=2\n", arr1_squeezed2)
print("This is the new shape of the squeezed array", arr1_squeezed2.shape)




This is our array:
 [[[1]
  [2]
  [3]]]
This is the current shape of the array (1, 3, 1)
This is our squeezed array, along the axis=0
 [[1]
 [2]
 [3]]
This is the new shape of the squeezed array (3, 1)
This is our squeezed array, along the axis=2
 [[1 2 3]]
This is the new shape of the squeezed array (1, 3)


It is also possible to squeeze a specific axis only. In the example above we squeezed axis=0 and axis=2, which are the only one-dimensionals axis.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([
      [1,2,3],
      [4,5,6]
    ])

print("This is our array:\n", arr1)
print("This is the current shape of the array", arr1.shape)

##Squeezing axis=0, which is not one-dimensional

arr1_squeezed0 = np.squeeze(arr1, axis=0)
print("This is our squeezed array, along the axis=0\n", arr1_squeezed0)
print("This is the new shape of the squeezed array", arr1_squeezed0.shape)

This is our array:
 [[1 2 3]
 [4 5 6]]
This is the current shape of the array (2, 3)


ValueError: ignored

In the example above we tried to squeeze axis=0, which is not one-dimensional. In fact, the error is quite self-explanatory: cannot select an axis to squeeze out which has size not equal to one



The np.squeeze function is useful to clean and better organize arrays that have been transformed many times.

##### Secondly, let's **roll** our dough and make a nice circular shape...
<img src="https://i.imgur.com/3LyeW4j.jpg"></img>
## Function 2 - **np.roll**

The np.roll function rolls elements inside an array along a given axis.

In [ ]:
# Example 1 - working
array = np.arange(4).reshape(2,2)
print("This is the original array\n", array)

#they see me rolling, they hating

rolled_array = np.roll(array, 1)
print("This is a rolled array, shifted by 1 position\n", rolled_array)

This is the original array
 [[0 1]
 [2 3]]
This is a rolled array, shifted by 1 position
 [[3 0]
 [1 2]]


Each element is shifted by one position to the right. The "3", which rolled beyond the last position is re-introduced at the beginning.

In [ ]:
# Example 2 - working
array2 = np.arange(9).reshape(3,3)
print("This is the original array\n", array2)

#rolling along the axis 0, shifting of one position (rows)
rolled_array_rows = np.roll(array2, 1, axis=0)
print("This is the rolled array\n", rolled_array_rows)



This is the original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
This is the rolled array
 [[6 7 8]
 [0 1 2]
 [3 4 5]]


In the example above, we shifted rows, not just elements. In fact, the last row is introduced at the beginning.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

array3 = np.arange(5)
print("This is the original array\n", array3)

#rolling
rolled_broken_array = np.roll(array3, 1, axis=1)
print("This won't be printed because it's not correct", rolled_broken_array)

This is the original array
 [0 1 2 3 4]


AxisError: ignored

Trying to roll along an axis which isn't part of the array will throw an error.

---



##### Then **flip** in the air your pizza, do it a couple of times and bake it...
<img src="https://i.imgur.com/KeELaTx.jpg"></img>
## Function 3 - **np.flip**

The np.flip function reverse elements inside an array along the given axis.

In [ ]:
# Example 1 - working
array = np.array([1,2,3,4,5])
print("This is the original array", array)
array_flipped = np.flip(array)
print("This is the flipped array", array_flipped)

This is the original array [1 2 3 4 5]
This is the flipped array [5 4 3 2 1]



This is a simple example with a 1D array, which has a single axis (axis=0)

In [ ]:
# Example 2 - working
array = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ])
print("This is the original array\n", array)
array_flipped = np.flip(array, axis=0)
print("This is the flipped array (axis=0)\n", array_flipped)
array_flipped_2 = np.flip(array, axis=1)
print("This is the flipped array (axis=1)\n", array_flipped_2)

This is the original array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
This is the flipped array (axis=0)
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
This is the flipped array (axis=1)
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


This is an example with a 2D array: specifying axis=0 we flipped the array's rows, while specifying axis=1 we flipped the array columns.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
array = np.array([1,2,3,4,5])
flipped_array = np.flip(array, axis=1)


AxisError: ignored

Trying to flip a dimension that doesn't exist (1D array only has axis=0, since it's a vector) will throw an error.

##### It's ready! Rembember to **split** and share your pizza with your friends. Don't be greedy.
<img src="https://i.imgur.com/AO8NcPz.jpg"></img>
## Function 4 - **np.split**

The np.split function is used to split arrays into sub-arrays.

In [43]:
# Example 1 - working
array = np.arange(10)
print("This is the original array:\n", array)

#splitting into 2 sub arrays
splitted_array = np.split(array, 2)
print("These are the 2 sub-arrays resulted:\n", splitted_array)

#splitting into 5 sub arrays
splitted_array_2 = np.split(array, 5)
print("These are the 5 sub-arrays resulted:\n", splitted_array_2)

This is the original array:
 [0 1 2 3 4 5 6 7 8 9]
These are the 2 sub-arrays resulted:
 [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
These are the 5 sub-arrays resulted:
 [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In the example above we splitted our original array into a set of 2 and 5 sub-arrays.


In [45]:
# Example 2 - working
array2 = np.arange(10)
print("This is the original array:\n", array2)

#splitting at certain points
splitted_array2 = np.split(array, [2,6,7])
print("These are the 4 sub-arrawys resulted:\n", splitted_array2)

This is the original array:
 [0 1 2 3 4 5 6 7 8 9]
These are the 4 sub-arrawys resulted:
 [array([0, 1]), array([2, 3, 4, 5]), array([6]), array([7, 8, 9])]


It is also possible to split using specific points at which the split must happen. In the example above, we splitted using this range [2,6,7], this is how NumPy did the thing:
from the 2nd element to the 6th [exluded],
from the 6th to the 6th element [just one],
from the 7th to the last element.

In [47]:
# Example 3 - breaking (to illustrate when it breaks)
array = np.arange(10)
print("This is the original array", array)

#Splitting
broken_array = np.split(array, 3)


This is the original array [0 1 2 3 4 5 6 7 8 9]


ValueError: ignored

Using the split method showed in the #1 example, it is important to choose a value that will make the divison equal. In this case, diving 10 elements by 3 will result in an error, bececause not all the elements will be equally distribuited. 

##### And, of course, pizza is never enough. Another round? We could call Just Eat this time, though.
<img src="https://i.imgur.com/HXsRw9s.jpg"></img>
## Function 5 - **np.repeat**

The np.repeat function is used to repeat elements inside an array (along the axis). If the axis is not specified, the function will flatten the original array and will output a flattened array.

In [ ]:
# Example 1 - working

#Repeating elements inside a 1D array
array = np.arange(5)
print("This is the original array:\n", array)

repeated_array = np.repeat(array, 2)
print("This is the repeated array, in which elements have been repeated twice(second parameter inside the function):\n", repeated_array)

This is the original array:
 [0 1 2 3 4]
This is the repeated array, in which elements have been repeated twice(second parameter inside the function):
 [0 0 1 1 2 2 3 3 4 4]


In the example above we repeated elements inside a simple 1D array.

In [37]:
# Example 2 - working
array = np.arange(9).reshape(3,3)
print("This is the original array\n",array)

#repeating along axis 0 (rows)
repeated_array_along_axis0 = np.repeat(array, 2, axis=0)
print("This is the repeated array along axis 0\n", repeated_array_along_axis0)

#repeating along axis 1 (columns)
repeated_array_along_axis1 = np.repeat(array, 2, axis=1)
print("This is the repeated array along axis 1\n", repeated_array_along_axis1)

This is the original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
This is the repeated array along axis 0
 [[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [6 7 8]
 [6 7 8]]
This is the repeated array along axis 1
 [[0 0 1 1 2 2]
 [3 3 4 4 5 5]
 [6 6 7 7 8 8]]


In the example above, we used the np.repeat function to repeat elements along rows or columns.

In [38]:
# Example 3 - breaking (to illustrate when it breaks)

array = np.arange(5)
print("This is the original array:\n", array)

repeated_array_broken = np.repeat(array, 2, axis=1)

This is the original array:
 [0 1 2 3 4]


AxisError: ignored

Trying to repeat along an axis which isn't supported by the array will throw and error.


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
